### PR TITLE
🐛 Update packages to get project to run

### PR DESCRIPTION
**Pull request by spjpgrd**

### CODE REVIEW

**Comment by clearab** [comment]
@Wajeed-msft Can you pull this down and verify please?

**Comment by Wajeed-msft** [comment]
@spjpgrd - What errors were you getting when you tried latest code? Is it failing while trying out something specific?

@clearab - I just did the clean build with latest code and I don't see any build error. 
image

**Comment by spjpgrd** [comment]
@Wajeed-msft — Heads down on a project right now, so just letting you know I'll get errors captured later in the day on Friday 👍

**Comment by jotrick** [comment]
@Wajeed-msft @clearab @spjpgrd  - just checked on this and verified. For me it didn't fix ALL of the build errors, but if fixed two of the three, so much appreciated! I think there are some issues with my local versions of things like npm, so I'll be pulling in a hot-fix for the last error shortly.

Thanks again for working to update this!

**Pull request merged**
